# coding: utf-8

"""
    Felt

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class LayerMetadata(BaseModel):
    """
    LayerMetadata
    """ # noqa: E501
    attribution_text: Optional[StrictStr] = 'not_provided'
    attribution_url: Optional[StrictStr] = 'not_provided'
    description: Optional[StrictStr] = 'not_provided'
    license: Optional[StrictStr] = 'not_provided'
    source_abbreviation: Optional[StrictStr] = 'not_provided'
    source_name: Optional[StrictStr] = 'not_provided'
    source_url: Optional[StrictStr] = 'not_provided'
    updated_at: Optional[date] = None
    __properties: ClassVar[List[str]] = ["attribution_text", "attribution_url", "description", "license", "source_abbreviation", "source_name", "source_url", "updated_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LayerMetadata from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if attribution_text (nullable) is None
        # and model_fields_set contains the field
        if self.attribution_text is None and "attribution_text" in self.model_fields_set:
            _dict['attribution_text'] = None

        # set to None if attribution_url (nullable) is None
        # and model_fields_set contains the field
        if self.attribution_url is None and "attribution_url" in self.model_fields_set:
            _dict['attribution_url'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['description'] = None

        # set to None if license (nullable) is None
        # and model_fields_set contains the field
        if self.license is None and "license" in self.model_fields_set:
            _dict['license'] = None

        # set to None if source_abbreviation (nullable) is None
        # and model_fields_set contains the field
        if self.source_abbreviation is None and "source_abbreviation" in self.model_fields_set:
            _dict['source_abbreviation'] = None

        # set to None if source_name (nullable) is None
        # and model_fields_set contains the field
        if self.source_name is None and "source_name" in self.model_fields_set:
            _dict['source_name'] = None

        # set to None if source_url (nullable) is None
        # and model_fields_set contains the field
        if self.source_url is None and "source_url" in self.model_fields_set:
            _dict['source_url'] = None

        # set to None if updated_at (nullable) is None
        # and model_fields_set contains the field
        if self.updated_at is None and "updated_at" in self.model_fields_set:
            _dict['updated_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LayerMetadata from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "attribution_text": obj.get("attribution_text") if obj.get("attribution_text") is not None else 'not_provided',
            "attribution_url": obj.get("attribution_url") if obj.get("attribution_url") is not None else 'not_provided',
            "description": obj.get("description") if obj.get("description") is not None else 'not_provided',
            "license": obj.get("license") if obj.get("license") is not None else 'not_provided',
            "source_abbreviation": obj.get("source_abbreviation") if obj.get("source_abbreviation") is not None else 'not_provided',
            "source_name": obj.get("source_name") if obj.get("source_name") is not None else 'not_provided',
            "source_url": obj.get("source_url") if obj.get("source_url") is not None else 'not_provided',
            "updated_at": obj.get("updated_at")
        })
        return _obj


