# coding: utf-8

"""
    Felt

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from felt_api.models.layer1_links import Layer1Links
from felt_api.models.layer_metadata import LayerMetadata
from typing import Optional, Set
from typing_extensions import Self

class Layer1(BaseModel):
    """
    Layer1
    """ # noqa: E501
    caption: Optional[StrictStr]
    geometry_type: Optional[StrictStr]
    hide_from_legend: StrictBool
    id: StrictStr
    is_spreadsheet: Optional[StrictBool] = None
    links: Optional[Layer1Links] = None
    metadata: Optional[LayerMetadata] = None
    name: StrictStr
    ordering_key: Optional[StrictInt] = Field(default=None, description="A sort order key used for ordering layers and layer groups in the legend")
    progress: Union[StrictFloat, StrictInt]
    refresh_period: Optional[StrictStr] = None
    status: StrictStr
    style: Dict[str, Any] = Field(description="The Felt Style Language style for the layer")
    subtitle: Optional[StrictStr] = Field(default=None, description="Deprecated: use `caption` instead.")
    tile_url: Optional[StrictStr] = Field(default=None, description="The tile URL for this layer")
    type: StrictStr
    __properties: ClassVar[List[str]] = ["caption", "geometry_type", "hide_from_legend", "id", "is_spreadsheet", "links", "metadata", "name", "ordering_key", "progress", "refresh_period", "status", "style", "subtitle", "tile_url", "type"]

    @field_validator('geometry_type')
    def geometry_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['Line', 'Point', 'Polygon', 'Raster']):
            raise ValueError("must be one of enum values ('Line', 'Point', 'Polygon', 'Raster')")
        return value

    @field_validator('refresh_period')
    def refresh_period_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['15 min', '30 min', 'hour', '3 hours', '6 hours', '12 hours', 'day', 'week', 'month', 'disabled']):
            raise ValueError("must be one of enum values ('15 min', '30 min', 'hour', '3 hours', '6 hours', '12 hours', 'day', 'week', 'month', 'disabled')")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['uploading', 'processing', 'failed', 'completed']):
            raise ValueError("must be one of enum values ('uploading', 'processing', 'failed', 'completed')")
        return value

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['layer']):
            raise ValueError("must be one of enum values ('layer')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Layer1 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of links
        if self.links:
            _dict['links'] = self.links.to_dict()
        # override the default output from pydantic by calling `to_dict()` of metadata
        if self.metadata:
            _dict['metadata'] = self.metadata.to_dict()
        # set to None if caption (nullable) is None
        # and model_fields_set contains the field
        if self.caption is None and "caption" in self.model_fields_set:
            _dict['caption'] = None

        # set to None if geometry_type (nullable) is None
        # and model_fields_set contains the field
        if self.geometry_type is None and "geometry_type" in self.model_fields_set:
            _dict['geometry_type'] = None

        # set to None if is_spreadsheet (nullable) is None
        # and model_fields_set contains the field
        if self.is_spreadsheet is None and "is_spreadsheet" in self.model_fields_set:
            _dict['is_spreadsheet'] = None

        # set to None if ordering_key (nullable) is None
        # and model_fields_set contains the field
        if self.ordering_key is None and "ordering_key" in self.model_fields_set:
            _dict['ordering_key'] = None

        # set to None if subtitle (nullable) is None
        # and model_fields_set contains the field
        if self.subtitle is None and "subtitle" in self.model_fields_set:
            _dict['subtitle'] = None

        # set to None if tile_url (nullable) is None
        # and model_fields_set contains the field
        if self.tile_url is None and "tile_url" in self.model_fields_set:
            _dict['tile_url'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Layer1 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "caption": obj.get("caption"),
            "geometry_type": obj.get("geometry_type"),
            "hide_from_legend": obj.get("hide_from_legend"),
            "id": obj.get("id"),
            "is_spreadsheet": obj.get("is_spreadsheet"),
            "links": Layer1Links.from_dict(obj["links"]) if obj.get("links") is not None else None,
            "metadata": LayerMetadata.from_dict(obj["metadata"]) if obj.get("metadata") is not None else None,
            "name": obj.get("name"),
            "ordering_key": obj.get("ordering_key"),
            "progress": obj.get("progress"),
            "refresh_period": obj.get("refresh_period"),
            "status": obj.get("status"),
            "style": obj.get("style"),
            "subtitle": obj.get("subtitle"),
            "tile_url": obj.get("tile_url"),
            "type": obj.get("type")
        })
        return _obj


