# coding: utf-8

"""
    Felt

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from felt_api.models.layer_metadata import LayerMetadata
from typing import Optional, Set
from typing_extensions import Self

class LayerParams(BaseModel):
    """
    LayerParams
    """ # noqa: E501
    caption: Optional[StrictStr] = 'not_provided'
    id: StrictStr
    layer_group_id: Optional[StrictStr] = 'not_provided'
    metadata: Optional[LayerMetadata] = None
    name: Optional[StrictStr] = 'not_provided'
    ordering_key: Optional[StrictInt] = None
    refresh_period: Optional[StrictStr] = None
    subtitle: Optional[StrictStr] = Field(default=None, description="Deprecated: use `caption` instead.")
    __properties: ClassVar[List[str]] = ["caption", "id", "layer_group_id", "metadata", "name", "ordering_key", "refresh_period", "subtitle"]

    @field_validator('refresh_period')
    def refresh_period_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['15 min', '30 min', 'hour', '3 hours', '6 hours', '12 hours', 'day', 'week', 'month', 'disabled']):
            raise ValueError("must be one of enum values ('15 min', '30 min', 'hour', '3 hours', '6 hours', '12 hours', 'day', 'week', 'month', 'disabled')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LayerParams from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of metadata
        if self.metadata:
            _dict['metadata'] = self.metadata.to_dict()
        # set to None if layer_group_id (nullable) is None
        # and model_fields_set contains the field
        if self.layer_group_id is None and "layer_group_id" in self.model_fields_set:
            _dict['layer_group_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LayerParams from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "caption": obj.get("caption") if obj.get("caption") is not None else 'not_provided',
            "id": obj.get("id"),
            "layer_group_id": obj.get("layer_group_id") if obj.get("layer_group_id") is not None else 'not_provided',
            "metadata": LayerMetadata.from_dict(obj["metadata"]) if obj.get("metadata") is not None else None,
            "name": obj.get("name") if obj.get("name") is not None else 'not_provided',
            "ordering_key": obj.get("ordering_key"),
            "refresh_period": obj.get("refresh_period"),
            "subtitle": obj.get("subtitle")
        })
        return _obj


