# coding: utf-8

"""
    Felt

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class MapCreateCustomExportRequest(BaseModel):
    """
    MapCreateCustomExportRequest
    """ # noqa: E501
    email_on_completion: Optional[StrictBool] = Field(default=None, description="Send an email to the requesting user when the export completes. Defaults to `true`")
    filters: Optional[List[Any]] = Field(default=None, description="Filters for the layer in specified in Felt Style Language filter format")
    output_format: StrictStr
    __properties: ClassVar[List[str]] = ["email_on_completion", "filters", "output_format"]

    @field_validator('output_format')
    def output_format_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['csv', 'gpkg', 'geojson']):
            raise ValueError("must be one of enum values ('csv', 'gpkg', 'geojson')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MapCreateCustomExportRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MapCreateCustomExportRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "email_on_completion": obj.get("email_on_completion"),
            "filters": obj.get("filters"),
            "output_format": obj.get("output_format")
        })
        return _obj


