# coding: utf-8

"""
    Felt

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class MapCreateRequest(BaseModel):
    """
    MapCreateRequest
    """ # noqa: E501
    basemap: Optional[StrictStr] = Field(default=None, description="The basemap to use for the new map. Defaults to \"default\". Valid values are \"default\", \"light\", \"dark\", \"satellite\", a valid raster tile URL with {x}, {y}, and {z} parameters, or a hex color string like #ff0000.")
    description: Optional[StrictStr] = Field(default=None, description="A description to display in the map legend")
    lat: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="If no data has been uploaded to the map, the initial latitude to center the map display on.")
    layer_urls: Optional[List[StrictStr]] = Field(default=None, description="An array of urls to use to create layers in the map. Only tile URLs for raster layers are supported at the moment.")
    lon: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="If no data has been uploaded to the map, the initial longitude to center the map display on.")
    public_access: Optional[StrictStr] = Field(default=None, description="The level of access to grant to the map. Defaults to \"view_only\".")
    title: Optional[StrictStr] = Field(default=None, description="The title to be used for the map. Defaults to \"Untitled Map\"")
    workspace_id: Optional[StrictStr] = Field(default=None, description="The workspace to create the map in. Defaults to the latest used workspace")
    zoom: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="If no data has been uploaded to the map, the initial zoom level for the map to display.")
    __properties: ClassVar[List[str]] = ["basemap", "description", "lat", "layer_urls", "lon", "public_access", "title", "workspace_id", "zoom"]

    @field_validator('public_access')
    def public_access_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['private', 'view_only', 'view_and_comment', 'view_comment_and_edit']):
            raise ValueError("must be one of enum values ('private', 'view_only', 'view_and_comment', 'view_comment_and_edit')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MapCreateRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MapCreateRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "basemap": obj.get("basemap"),
            "description": obj.get("description"),
            "lat": obj.get("lat"),
            "layer_urls": obj.get("layer_urls"),
            "lon": obj.get("lon"),
            "public_access": obj.get("public_access"),
            "title": obj.get("title"),
            "workspace_id": obj.get("workspace_id"),
            "zoom": obj.get("zoom")
        })
        return _obj


