# coding: utf-8

"""
    Felt

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from felt_api.models.source_permissions_project_editors import SourcePermissionsProjectEditors
from felt_api.models.source_permissions_source_owner import SourcePermissionsSourceOwner
from felt_api.models.source_permissions_workspace_editors import SourcePermissionsWorkspaceEditors
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

SOURCECREATEPARAMSPERMISSIONS_ONE_OF_SCHEMAS = ["SourcePermissionsProjectEditors", "SourcePermissionsSourceOwner", "SourcePermissionsWorkspaceEditors"]

class SourceCreateParamsPermissions(BaseModel):
    """
    SourceCreateParamsPermissions
    """
    # data type: SourcePermissionsWorkspaceEditors
    oneof_schema_1_validator: Optional[SourcePermissionsWorkspaceEditors] = None
    # data type: SourcePermissionsSourceOwner
    oneof_schema_2_validator: Optional[SourcePermissionsSourceOwner] = None
    # data type: SourcePermissionsProjectEditors
    oneof_schema_3_validator: Optional[SourcePermissionsProjectEditors] = None
    actual_instance: Optional[Union[SourcePermissionsProjectEditors, SourcePermissionsSourceOwner, SourcePermissionsWorkspaceEditors]] = None
    one_of_schemas: Set[str] = { "SourcePermissionsProjectEditors", "SourcePermissionsSourceOwner", "SourcePermissionsWorkspaceEditors" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = SourceCreateParamsPermissions.model_construct()
        error_messages = []
        match = 0
        # validate data type: SourcePermissionsWorkspaceEditors
        if not isinstance(v, SourcePermissionsWorkspaceEditors):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SourcePermissionsWorkspaceEditors`")
        else:
            match += 1
        # validate data type: SourcePermissionsSourceOwner
        if not isinstance(v, SourcePermissionsSourceOwner):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SourcePermissionsSourceOwner`")
        else:
            match += 1
        # validate data type: SourcePermissionsProjectEditors
        if not isinstance(v, SourcePermissionsProjectEditors):
            error_messages.append(f"Error! Input type `{type(v)}` is not `SourcePermissionsProjectEditors`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in SourceCreateParamsPermissions with oneOf schemas: SourcePermissionsProjectEditors, SourcePermissionsSourceOwner, SourcePermissionsWorkspaceEditors. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in SourceCreateParamsPermissions with oneOf schemas: SourcePermissionsProjectEditors, SourcePermissionsSourceOwner, SourcePermissionsWorkspaceEditors. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into SourcePermissionsWorkspaceEditors
        try:
            instance.actual_instance = SourcePermissionsWorkspaceEditors.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SourcePermissionsSourceOwner
        try:
            instance.actual_instance = SourcePermissionsSourceOwner.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into SourcePermissionsProjectEditors
        try:
            instance.actual_instance = SourcePermissionsProjectEditors.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into SourceCreateParamsPermissions with oneOf schemas: SourcePermissionsProjectEditors, SourcePermissionsSourceOwner, SourcePermissionsWorkspaceEditors. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into SourceCreateParamsPermissions with oneOf schemas: SourcePermissionsProjectEditors, SourcePermissionsSourceOwner, SourcePermissionsWorkspaceEditors. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], SourcePermissionsProjectEditors, SourcePermissionsSourceOwner, SourcePermissionsWorkspaceEditors]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


