# coding: utf-8

"""
    Felt

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from felt_api.models.source_permissions import SourcePermissions
from felt_api.models.source_reference_links import SourceReferenceLinks
from typing import Optional, Set
from typing_extensions import Self

class SourceReference(BaseModel):
    """
    SourceReference
    """ # noqa: E501
    automatic_sync: Optional[StrictStr] = None
    connection_type: Optional[StrictStr] = None
    created_at: Optional[StrictInt] = None
    id: Optional[StrictStr] = None
    last_synced_at: Optional[StrictInt] = None
    links: Optional[SourceReferenceLinks] = None
    name: Optional[StrictStr] = None
    owner_id: Optional[StrictStr] = None
    permissions: Optional[SourcePermissions] = None
    sync_status: Optional[StrictStr] = None
    type: Optional[StrictStr] = None
    updated_at: Optional[StrictInt] = None
    workspace_id: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["automatic_sync", "connection_type", "created_at", "id", "last_synced_at", "links", "name", "owner_id", "permissions", "sync_status", "type", "updated_at", "workspace_id"]

    @field_validator('automatic_sync')
    def automatic_sync_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['enabled', 'paused']):
            raise ValueError("must be one of enum values ('enabled', 'paused')")
        return value

    @field_validator('connection_type')
    def connection_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['bigquery', 'databricks', 'feature_server', 'mssql', 'ogc', 'postgresql', 'redshift', 'sentinel_hub', 'snowflake', 'stac', 'wfs', 'wms_wmts']):
            raise ValueError("must be one of enum values ('bigquery', 'databricks', 'feature_server', 'mssql', 'ogc', 'postgresql', 'redshift', 'sentinel_hub', 'snowflake', 'stac', 'wfs', 'wms_wmts')")
        return value

    @field_validator('sync_status')
    def sync_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['syncing', 'completed', 'failed']):
            raise ValueError("must be one of enum values ('syncing', 'completed', 'failed')")
        return value

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['source_reference']):
            raise ValueError("must be one of enum values ('source_reference')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SourceReference from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of links
        if self.links:
            _dict['links'] = self.links.to_dict()
        # override the default output from pydantic by calling `to_dict()` of permissions
        if self.permissions:
            _dict['permissions'] = self.permissions.to_dict()
        # set to None if created_at (nullable) is None
        # and model_fields_set contains the field
        if self.created_at is None and "created_at" in self.model_fields_set:
            _dict['created_at'] = None

        # set to None if last_synced_at (nullable) is None
        # and model_fields_set contains the field
        if self.last_synced_at is None and "last_synced_at" in self.model_fields_set:
            _dict['last_synced_at'] = None

        # set to None if updated_at (nullable) is None
        # and model_fields_set contains the field
        if self.updated_at is None and "updated_at" in self.model_fields_set:
            _dict['updated_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SourceReference from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "automatic_sync": obj.get("automatic_sync"),
            "connection_type": obj.get("connection_type"),
            "created_at": obj.get("created_at"),
            "id": obj.get("id"),
            "last_synced_at": obj.get("last_synced_at"),
            "links": SourceReferenceLinks.from_dict(obj["links"]) if obj.get("links") is not None else None,
            "name": obj.get("name"),
            "owner_id": obj.get("owner_id"),
            "permissions": SourcePermissions.from_dict(obj["permissions"]) if obj.get("permissions") is not None else None,
            "sync_status": obj.get("sync_status"),
            "type": obj.get("type"),
            "updated_at": obj.get("updated_at"),
            "workspace_id": obj.get("workspace_id")
        })
        return _obj


