# coding: utf-8

"""
    Felt

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class UploadResponse(BaseModel):
    """
    UploadResponse
    """ # noqa: E501
    layer_group_id: Optional[StrictStr] = None
    layer_id: Optional[StrictStr] = Field(default=None, description="The ID of the layer created by this upload. If multiple layers are included in the upload, this is the ID of the first layer in the layer group.")
    presigned_attributes: Optional[Dict[str, Any]] = Field(default=None, description="If provided, the presigned attributes to attach to the post request")
    type: Optional[StrictStr] = None
    url: Optional[StrictStr] = Field(default=None, description="If provided, the URL to post the file to")
    __properties: ClassVar[List[str]] = ["layer_group_id", "layer_id", "presigned_attributes", "type", "url"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['upload_response']):
            raise ValueError("must be one of enum values ('upload_response')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UploadResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if presigned_attributes (nullable) is None
        # and model_fields_set contains the field
        if self.presigned_attributes is None and "presigned_attributes" in self.model_fields_set:
            _dict['presigned_attributes'] = None

        # set to None if url (nullable) is None
        # and model_fields_set contains the field
        if self.url is None and "url" in self.model_fields_set:
            _dict['url'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UploadResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "layer_group_id": obj.get("layer_group_id"),
            "layer_id": obj.get("layer_id"),
            "presigned_attributes": obj.get("presigned_attributes"),
            "type": obj.get("type"),
            "url": obj.get("url")
        })
        return _obj


